/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (store reachable, watcher health) */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document */
        get: operations["getOpenApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interactive/{id}": {
        parameters: {
            query?: {
                /** @description Interactive token (alternative to the Authorization header). */
                token?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /**
         * Load a transaction for the interactive pages
         * @description Accepts the interactive token, or the read-only `more_info_url` token.
         */
        get: operations["getInteractive"];
        put?: never;
        /** Submit the deposit/withdraw form */
        post: operations["submitInteractive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/rail/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rail event (signed, idempotent)
         * @description Signed with `Zephyr-Signature: t=<unix seconds>,v1=<hex HMAC-SHA256(RAIL_WEBHOOK_SECRET, "<t>.<raw body>")>`.
         *     Timestamps older than 5 minutes are rejected. Each event `id` (or
         *     `Idempotency-Key` header) is processed at most once. Registered only when
         *     RAIL_WEBHOOK_SECRET is set. See docs/payment-rails.md.
         */
        post: operations["railWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/deposits/{id}/fiat-received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate the user's dollars arriving */
        post: operations["sandboxFiatReceived"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/withdrawals/{id}/stellar-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate a standard withdrawal's USDC payment arriving */
        post: operations["sandboxStellarPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/withdrawals/{id}/escrow-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate the wallet locking USDC in the sandbox escrow
         * @description Only with the in-memory sandbox escrow (no ESCROW_CONTRACT_ID).
         */
        post: operations["sandboxEscrowLock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/withdrawals/{id}/escrow-refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance the sandbox ledger and refund an expired escrow */
        post: operations["sandboxEscrowRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/escrow/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance the sandbox ledger */
        post: operations["sandboxEscrowAdvance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/transactions/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every status transition recorded for a transaction */
        get: operations["sandboxAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /**
         * @description Decimal string with up to 7 decimal places. Never a float.
         * @example 100.00
         */
        Amount: string;
        /**
         * @description SEP-24 transaction status.
         * @enum {string}
         */
        TransactionStatus: "incomplete" | "pending_user_transfer_start" | "pending_user_transfer_complete" | "pending_external" | "pending_anchor" | "pending_stellar" | "pending_trust" | "pending_user" | "completed" | "refunded" | "expired" | "no_market" | "too_small" | "too_large" | "error";
        Refunds: {
            amount_refunded: components["schemas"]["Amount"];
            amount_fee: components["schemas"]["Amount"];
            payments: {
                id: string;
                /** @enum {unknown} */
                id_type: "stellar" | "external";
                amount: components["schemas"]["Amount"];
                fee: components["schemas"]["Amount"];
            }[];
        };
        /** @description Zephyr extension on escrow withdrawals. */
        EscrowDetails: {
            contract_id: string;
            /** @description Hex sha256 of the transaction id; the escrow's `tx_id`. */
            tx_id: string;
            amount: components["schemas"]["Amount"] | null;
            timeout_ledgers: number;
            expires_ledger?: number | null;
            lock_tx_hash?: string | null;
            claim_tx_hash?: string | null;
            refund_tx_hash?: string | null;
        };
        /** @description SEP-24 transaction object, plus Zephyr's escrow extension. */
        Transaction: {
            /** Format: uuid */
            id: string;
            /** @enum {unknown} */
            kind: "deposit" | "withdrawal";
            status: components["schemas"]["TransactionStatus"];
            /** Format: uri */
            more_info_url: string;
            amount_in?: components["schemas"]["Amount"] | null;
            amount_out?: components["schemas"]["Amount"] | null;
            amount_fee?: components["schemas"]["Amount"] | null;
            amount_in_asset?: string;
            amount_out_asset?: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            completed_at?: string | null;
            stellar_transaction_id?: string | null;
            external_transaction_id?: string | null;
            message?: string | null;
            refunded: boolean;
            refunds?: components["schemas"]["Refunds"];
            to?: string | null;
            deposit_memo?: string | null;
            deposit_memo_type?: string | null;
            from?: string | null;
            withdraw_anchor_account?: string | null;
            withdraw_memo?: string | null;
            withdraw_memo_type?: string | null;
            /** @enum {unknown} */
            withdraw_mode?: "standard" | "escrow";
            escrow?: components["schemas"]["EscrowDetails"];
        };
        InteractiveView: {
            transaction: components["schemas"]["Transaction"];
            /** @description True while the form can still be submitted. */
            editable: boolean;
            /** @example en */
            lang: string;
            asset: {
                code: string;
                issuer: string;
            };
            limits: {
                min: components["schemas"]["Amount"];
                max: components["schemas"]["Amount"];
            };
            /** @description fee = fixed + amount * percent / 100, rounded half-up to cents. */
            fee: {
                fixed: components["schemas"]["Amount"];
                /** @example 1 */
                percent: string;
            };
            deposit_instructions: {
                [key: string]: string;
            } | null;
            escrow: {
                /** @constant */
                enabled: false;
            } | {
                /** @constant */
                enabled: true;
                contract_id: string | null;
                timeout_ledgers: number;
                network_passphrase: string;
                /** Format: uri */
                soroban_rpc_url: string;
            };
        };
        InteractiveSubmit: {
            amount: components["schemas"]["Amount"];
            name: string;
            /** Format: email */
            email: string;
            /** @enum {unknown} */
            withdraw_mode?: "standard" | "escrow";
        };
        RailEvent: {
            id: string;
            /** @constant */
            type: "deposit.received";
            data: {
                transaction_id: string;
                amount: components["schemas"]["Amount"];
                external_id?: string;
            };
        } | {
            id: string;
            /** @constant */
            type: "payout.completed";
            data: {
                transaction_id: string;
                external_id?: string;
            };
        } | {
            id: string;
            /** @constant */
            type: "payout.failed";
            data: {
                transaction_id: string;
                reason?: string;
            };
        };
        Readiness: {
            /** @enum {unknown} */
            status: "ready" | "not_ready";
            checks: {
                [key: string]: string;
            };
        };
        AuditEntry: {
            transactionId: string;
            fromStatus: components["schemas"]["TransactionStatus"] | null;
            toStatus: components["schemas"]["TransactionStatus"];
            actor: string;
            note?: string;
            /** Format: date-time */
            at: string;
        };
    };
    responses: {
        /** @description Error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The transaction. */
        Transaction: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    transaction: components["schemas"]["Transaction"];
                };
            };
        };
    };
    parameters: {
        TransactionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                        /** @enum {unknown} */
                        network: "testnet" | "public";
                        rail: string;
                    };
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready for traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description A dependency is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    getOpenApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": unknown;
                };
            };
        };
    };
    getInteractive: {
        parameters: {
            query?: {
                /** @description Interactive token (alternative to the Authorization header). */
                token?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The transaction and everything the form needs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractiveView"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    submitInteractive: {
        parameters: {
            query?: {
                /** @description Interactive token (alternative to the Authorization header). */
                token?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractiveSubmit"];
            };
        };
        responses: {
            /** @description Updated transaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractiveView"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    railWebhook: {
        parameters: {
            query?: never;
            header: {
                "Zephyr-Signature": string;
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Must equal the configured PAYMENT_RAIL name. */
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RailEvent"];
            };
        };
        responses: {
            /** @description Processed, or a duplicate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        received: true;
                        duplicate: boolean;
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    sandboxFiatReceived: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Transaction"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    sandboxStellarPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    amount?: components["schemas"]["Amount"];
                };
            };
        };
        responses: {
            200: components["responses"]["Transaction"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    sandboxEscrowLock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    amount?: components["schemas"]["Amount"];
                    from?: string;
                    timeout_ledgers?: number;
                };
            };
        };
        responses: {
            200: components["responses"]["Transaction"];
            409: components["responses"]["Error"];
        };
    };
    sandboxEscrowRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    advance_ledgers?: number;
                };
            };
        };
        responses: {
            200: components["responses"]["Transaction"];
            409: components["responses"]["Error"];
        };
    };
    sandboxEscrowAdvance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    ledgers?: number;
                };
            };
        };
        responses: {
            /** @description New ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ledger?: number;
                    };
                };
            };
        };
    };
    sandboxAuditLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        audit: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
